## numpy array and basics


In [1]:
import numpy  as np

In [2]:
arr_1d = np.array([1,2,3,3,6,5])
print("1D array:", arr_1d)
arr_2d = np.array([[1,2,3,3,6,5], [1,2,3,3,6,5]])
print("2D array:", arr_2d)

1D array: [1 2 3 3 6 5]
2D array: [[1 2 3 3 6 5]
 [1 2 3 3 6 5]]


###list vs numpy


In [4]:
py_list = [1,2,3,]
print("Python list multiplication", py_list * 2)
arr_1d = np.array([1,2,3,3,6,5])
print("Python array multiplication", arr_1d * 2)

Python list multiplication [1, 2, 3, 1, 2, 3]
Python array multiplication [ 2  4  6  6 12 10]


In [11]:
import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operatin time: ", time.time() - start)

start = time.time()
arr_1d = np.arange(1000000) * 2
print("\n numpy operatin time: ", time.time() - start)


 List operatin time:  0.07643795013427734

 numpy operatin time:  0.006989479064941406


In [ ]:
###creating array from scratch


In [12]:
ones = np.ones((2,3))
print("one array: \n",ones)

one array: 
 [[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
full = np.full((2,2),7)
print("full array: \n", full)

full array: 
 [[7 7]
 [7 7]]


In [15]:
###random
random = np.random.random((2,3)) 
print("random array : \n", random)

random array : 
 [[0.79135804 0.87643951 0.79889584]
 [0.25896051 0.95218064 0.48743801]]


In [18]:
sequence = np.arange(0, 10, 2)
print("sequence array: \n", sequence)

sequence array: 
 [0 2 4 6 8]


###vector, matrix and tensor


In [20]:
vector = np.array ([1,2,3])
print("vector:", vector)

matrix = np.array([[1,2,3],[ 4,5,6]])
print("matrix:", matrix)
 
 
tensor = np.array([[1,2],[1,2],[1,2],[1,2]])
print("tensor:", tensor)

vector: [1 2 3]
matrix: [[1 2 3]
 [4 5 6]]
tensor: [[1 2]
 [1 2]
 [1 2]
 [1 2]]


###array properties


In [21]:
arr = np.array([[1, 2, 3], [5, 5, 6]])
print("Shape", arr.shape)
print("Dimension", arr.ndim)
print("Size", arr.size)
print("Dtype", arr.dtype)

Shape (2, 3)
Dimension 2
Size 6
Dtype int64


array reshaping

In [ ]:
arr = np.arange(0, 10)
print("original aar",arr)

reshaped= arr.reshape((3,4))
print()



original aar [0 1 2 3 4 5 6 7 8 9]


ValueError: cannot reshape array of size 10 into shape (3,4)