numpy array operation

In [3]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5,6,7,8,9])

print("Basic Slicing", arr[2:7])
print("With Step", arr[1:8:2])
print("Negative indexing", arr[-3])

Basic Slicing [3 4 5 6 7]
With Step [2 4 6 8]
Negative indexing 7


In [8]:
arr_2d = np.array([[1,2,3,4],[1,2,3,4]])
print("arr_2d", arr_2d)

print("Specific  element", arr_2d[1,3] )
print("Entire row", arr_2d[1])
print("Entire row", arr_2d[:,2])

arr_2d [[1 2 3 4]
 [1 2 3 4]]
Specific  element 4
Entire row [1 2 3 4]
Entire row [3 3]


#sorting


In [19]:
unsorted = np.array([3,2,1,6,5,7])
print("Sorted Array", np.sort(unsorted))
arr_2d_unsorted = np.array([[8,12],[2,1],[4,9] ])
#Operate column-wise (down each column)
print("Sorted 2D array by column", np.sort(arr_2d_unsorted, axis=0))
#Operate row-wise (across each row)
print("Sorted 2D array by column", np.sort(arr_2d_unsorted, axis=1))



Sorted Array [1 2 3 5 6 7]
Sorted 2D array by column [[ 2  1]
 [ 4  9]
 [ 8 12]]
Sorted 2D array by column [[ 8 12]
 [ 1  2]
 [ 4  9]]


#filter


In [23]:
number = np.array([1,2,3,4,5,6,7,8,9])
print("number", number)

even_number = number[number % 2 == 0]
print("even numvers",even_number)


number [1 2 3 4 5 6 7 8 9]
even numvers [2 4 6 8]


In [27]:
#filter with mask
mask = number > 5
print("numbers greater than 5", number[mask]) 

numbers greater than 5 [6 7 8 9]


In [29]:
#fanxy indexing vs np.where()

indices = [0,2,4]
print(number[indices])

where_result = np.where(number>5)
print("NP where", number[where_result])

[1 3 5]
NP where [6 7 8 9]


In [31]:
condition_array = np.where(number>5, number*2,number)
print(condition_array)

[ 1  2  3  4  5 12 14 16 18]


In [ ]:
#adding and removing data
number1 = np.array([1,2,3,4,5,6,7,8,9])
number2 = np.array([1,2,3,4,5,6,7,8,9])
combined = np.concatenate((number1,number2))
print("number3 :",combined)


number3 : [1 2 3 4 5 6 7 8 9 1 2 3 4 5 6 7 8 9]


In [35]:
#arr compatibility
number1 = np.array([1,2,3,4,5,6,7,8,9])
number2 = np.array([1,2,3,4,5,6,7,8,9])

print("compatibility shapes", number1.shape == number2.shape)


compatibility shapes True


In [ ]:
number1 = np.array([1,2,3,4,5,6,7,8,9])
new_row = np.array([[1,2,3,4,5,6,7,8,9]])
#vstack=row
new = np.vstack((number1, new_row))
print("new", new)




new [[1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]]


In [ ]:
#hstack = coloum
number5 = np.array([[1,2],[3,4],[5,6]])
new_column = np.array([[8],[9],[5]])
new1 = np.hstack((number5,new_column))
print("new1", new1)

new1 [[1 2 8]
 [3 4 9]
 [5 6 5]]


In [44]:
number1 = np.array([1,2,3,4,5,6,7,8,9])
deleted = np.delete(arr,2)
print("deleted",deleted)

deleted [1 2 4 5 6 7 8 9]


Advanced operation with business examples


In [ ]:
#data structure:[resturent_id,2021,2022,2023,2024]
sales_data = np.array([
   [1,15000,18000,220000,25000], #paraise
   [2,16000,19000,230000,26000], #beijing
   [3,17000,20000,210000,27000], #pizza
   [4,18000,21000,220000,28000], #burger
   [5,19000,22000,230000,26000]  #chai
])
print("sales_data", sales_data)



sales_data [[     1  15000  18000 220000  25000]
 [     2  16000  19000 230000  26000]
 [     3  17000  20000 210000  27000]
 [     4  18000  21000 220000  28000]
 [     5  19000  22000 230000  26000]]
